const ActionsType = {
    LOADING: "LOADING",
    AUTH: "AUTH",
    LOAD_IMAGES: "LOAD_IMAGES",
    ADD_NEW_PROJECT: "ADD_NEW_PROJECT",
    GET_PROJECTS: "GET_PROJECTS",
    UPDATE_PROJECTS: "UPDATE_PROJECTS",
    DELETE_PROJECTS: "DELETE_PROJECTS",
}

export default ActionsType;